language: rust
rust: stable

script:
  - cargo build --release

matrix:
  include:
    - os: linux
      before_deploy: ci/linux.sh
    - os: windows
      before_deploy: ci/windows.sh


deploy:
  provider: releases
  api_key:
    secure: $GITHUB_RELEASES_KEY
  file: dist/*
  skip_cleanup: true
  draft: true
