language: rust
rust: stable

before_install:
  - sudo apt-get update
  - sudo apt-get -y install zip gcc-mingw-w64-i686 gcc-mingw-w64-x86-64
  - rustup target add x86_64-pc-windows-gnu
  - rustup target add i686-pc-windows-gnu
  - rustup target add x86_64-unknown-linux-gnu

# The entire build has to go in before_deploy because Travis doesn't provide a way to keep these files around.
# Also no 32-bit linux because Travis only supports up to Ubuntu 16 (xenial) while the gcc-i686-linux-gnu compiler
# (necessary for 32-bit linux compilation) is only available starting with Bionic (18.04 LTS) and up.
before_deploy:
  - mkdir -p dist
  - cargo rustc --release --target=x86_64-pc-windows-gnu -- -C linker=x86_64-w64-mingw32-gcc
  - zip -Tj dist/project-cleanup-win64.zip target/x86_64-pc-windows-gnu/release/project-cleanup.exe
  - cargo rustc --release --target=i686-pc-windows-gnu -- -C linker=i686-w64-mingw32-gcc -C link-args=-mwindows -C panic=abort
  - zip -Tj dist/project-cleanup-win32.zip target/i686-pc-windows-gnu/release/project-cleanup.exe
  - cargo rustc --release --target=x86_64-unknown-linux-gnu
  - zip -Tj dist/project-cleanup-linux.zip target/x86_64-unknown-linux-gnu/release/project-cleanup
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_RELEASES_KEY
  file_glob: true
  file: dist/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
