name: Build

on: [create]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run build
        run: build.sh
        shell: sh

      - name: Upload binaries
        uses: actions/upload-artifact@v1.0.0
        with:
          name: project-cleanup-build
          path: dist
