name: tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test --verbose
